import React from 'react';
import { Table } from 'reactstrap';

const RAMTable = (props) => {
	return (
		<div style={{ overflowY: 'scroll', width: '30%', alignSelf: 'flex-start', marginTop: '23px', height: '90vh' }}>
			<Table dark>
				<thead>
					<tr>
						<th>Label</th>
						<th>Address</th>
						<th>Instruction</th>
						<th>Hex</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Mark</td>
						<td>Otto</td>
						<td>@mdo</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Jacob</td>
						<td>Thornton</td>
						<td>@fat</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Larry</td>
						<td>the Bird</td>
						<td>@twitter</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Mark</td>
						<td>Otto</td>
						<td>@mdo</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Jacob</td>
						<td>Thornton</td>
						<td>@fat</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Larry</td>
						<td>the Bird</td>
						<td>@twitter</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Mark</td>
						<td>Otto</td>
						<td>@mdo</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Jacob</td>
						<td>Thornton</td>
						<td>@fat</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Larry</td>
						<td>the Bird</td>
						<td>@twitter</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Mark</td>
						<td>Otto</td>
						<td>@mdo</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Jacob</td>
						<td>Thornton</td>
						<td>@fat</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Larry</td>
						<td>the Bird</td>
						<td>@twitter</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Mark</td>
						<td>Otto</td>
						<td>@mdo</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Jacob</td>
						<td>Thornton</td>
						<td>@fat</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Larry</td>
						<td>the Bird</td>
						<td>@twitter</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Mark</td>
						<td>Otto</td>
						<td>@mdo</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Jacob</td>
						<td>Thornton</td>
						<td>@fat</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Larry</td>
						<td>the Bird</td>
						<td>@twitter</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Mark</td>
						<td>Otto</td>
						<td>@mdo</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Jacob</td>
						<td>Thornton</td>
						<td>@fat</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Larry</td>
						<td>the Bird</td>
						<td>@twitter</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Mark</td>
						<td>Otto</td>
						<td>@mdo</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Jacob</td>
						<td>Thornton</td>
						<td>@fat</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Larry</td>
						<td>the Bird</td>
						<td>@twitter</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Mark</td>
						<td>Otto</td>
						<td>@mdo</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Jacob</td>
						<td>Thornton</td>
						<td>@fat</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Larry</td>
						<td>the Bird</td>
						<td>@twitter</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Mark</td>
						<td>Otto</td>
						<td>@mdo</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Jacob</td>
						<td>Thornton</td>
						<td>@fat</td>
						<td>0321</td>
					</tr>
					<tr>
						<td>Larry</td>
						<td>the Bird</td>
						<td>@twitter</td>
						<td>0321</td>
					</tr>
				</tbody>
			</Table>
		</div>
	);
};

export default RAMTable;
